dueño = input("Nombre de quien trajo al animal a la veterinaria ")
animaltipo = input("Que tipo de animal es? ")
nombreanimal = input("Cual es el nombre del animal? ")
Raza = input("Que raza es el animal? ")
consulta = input("cual es la razon de la consulta al veterinario ")
consultavalor = float(input("Valor de la consulta: " ))
medicamento = float(input("Valor de medicamentos suministrados" ))
vacunas = float(input("Valor de vacunas inyectadas" ))

subtotalconsulta = consultavalor + medicamento + vacunas
ivavalor = subtotalconsulta * 0.19
totalconsulta = subtotalconsulta + ivavalor

print("")
print("----------------------------------------------------")
print("")
print("factura de consulta veterinaria")
print("")
print("----------------------------------------------------")
print("")
print("Responsable del animal: ", dueño)
print("")
print("tipo de animal: ", animaltipo)
print("")
print("Raza de animal: ", Raza)
print("")
print("Nombre del animal: ", nombreanimal)
print("")
print("Razon de la consulta: ", consulta)
print("")
print("Subtotal de la consulta (medicamentos, vacunas, revision) es: ", subtotalconsulta)
print("")
print("Impuestos: ", ivavalor)
print("")
print("Valor total de la consulta: ", totalconsulta)
print("")
print("----------------------------------------------------")
print("")
print("Gracias por preferir nuestra clinica veterinaria le deseamos la mejor salud a tu animal ")
print("")